### ISSUE TITLE
呃呃呃

### ISSUE THREAD

**Issue by dengchenglin** [Arc-lin/ALNetworking#1]
哥们，你不觉得把简单的事情复杂化了么，
RAC使用的有点过了，随便一个signal就几十个调用栈，追溯代码多费劲呀
如果要用到RAC组合相关的功能，完全可以在viewModel再去包装RACSignal呀

**Comment by dengchenglin** [comment]
毕竟大部分情况下网络请求没有这些场景

**Comment by Arc-lin** [comment]
因为想到MVVM的网络请求是用RACCommand封装的，然后RACCommand内返回的又是RACSignal，所以自然而然就会想到用RACSigal包装网络请求，也就这样而已
如果不用RACCommand包装网络请求也是可以的，这里面有利有弊吧。
